### ISSUE TITLE
Error in dbt run sample model on presto

### ISSUE THREAD

**Issue by rmgpinto** [fishtown-analytics/dbt-presto#3]
### Issue description
I'm testing dbt for presto.
Just ran:
```
$ dbt init test
$ cd test && dbt run
```

### Results
```
Running with dbt=0.13.0
Found 1 models, 0 tests, 0 archives, 0 analyses, 96 macros, 0 operations, 0 seed files, 0 sources

13:18:07 | Concurrency: 4 threads (target='dev')
13:18:07 | 
13:18:07 | 1 of 1 START view model data_warehouse.my_first_dbt_model............ [RUN]
13:18:09 | 1 of 1 ERROR creating view model data_warehouse.my_first_dbt_model... [ERROR in 1.05s]
13:18:09 | 
13:18:09 | Finished running 1 view models in 7.50s.

Completed with 1 errors:

Runtime Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
  PrestoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Unsupported combination of operations in a single transaction", query_id=20190414_131810_00009_qvqzx)

Done. PASS=0 ERROR=1 SKIP=0 TOTAL=1
```

### System information
The output of `dbt --version`:
```
installed version: 0.13.0
   latest version: 0.13.0

Up to date!
```

The operating system you're running on:
docker image: `amazonlinux`

The python version you're using (probably the output of `python --version`)
```
$ python3 --version
Python 3.7.2
```

Presto version: 0.215 (AWS EMR)

### dbt.log

```
2019-04-17 11:00:52,473 (MainThread): 11:00:52 | Concurrency: 1 threads (target='dev')
2019-04-17 11:00:52,473 (MainThread): 11:00:52 | 
2019-04-17 11:00:52,479 (Thread-1): 11:00:52 | 1 of 1 START view model data_warehouse.my_first_dbt_model............ [RUN]
2019-04-17 11:00:52,479 (Thread-1): Compiling model.my_new_package.my_first_dbt_model
2019-04-17 11:00:52,486 (Thread-1): Writing injected SQL for node "model.my_new_package.my_first_dbt_model"
2019-04-17 11:00:52,529 (Thread-1): Acquiring new presto connection "my_first_dbt_model".
2019-04-17 11:00:52,530 (Thread-1): Re-using an available connection from the pool.
2019-04-17 11:00:52,530 (Thread-1): Using presto connection "my_first_dbt_model".
2019-04-17 11:00:52,530 (Thread-1): On my_first_dbt_model: drop view if exists "data_lake"."data_warehouse"."my_first_dbt_model__dbt_tmp"
2019-04-17 11:00:52,717 (Thread-1): SQL status: OK in 0.19 seconds
2019-04-17 11:00:52,726 (Thread-1): Using presto connection "my_first_dbt_model".
2019-04-17 11:00:52,727 (Thread-1): On my_first_dbt_model: drop view if exists "data_lake"."data_warehouse"."my_first_dbt_model__dbt_backup"
2019-04-17 11:00:52,876 (Thread-1): SQL status: OK in 0.15 seconds
2019-04-17 11:00:52,878 (Thread-1): Writing runtime SQL for node "model.my_new_package.my_first_dbt_model"
2019-04-17 11:00:53,013 (Thread-1): Using presto connection "my_first_dbt_model".
2019-04-17 11:00:53,013 (Thread-1): On my_first_dbt_model: create view "data_lake"."data_warehouse"."my_first_dbt_model__dbt_tmp" as (
    -- Welcome to your first dbt model!
-- Did you know that you can also configure models directly within
-- the SQL file? This will override configurations stated in dbt_project.yml

-- Try changing 'view' to 'table', then re-running dbt



select 1 as id
  )
2019-04-17 11:00:53,205 (Thread-1): SQL status: OK in 0.19 seconds
2019-04-17 11:00:53,210 (Thread-1): Using presto connection "my_first_dbt_model".
2019-04-17 11:00:53,210 (Thread-1): On my_first_dbt_model: alter table "data_lake"."data_warehouse"."my_first_dbt_model__dbt_tmp" rename to "data_lake"."data_warehouse"."my_first_dbt_model"
2019-04-17 11:00:53,356 (Thread-1): Error while running:
alter table "data_lake"."data_warehouse"."my_first_dbt_model__dbt_tmp" rename to "data_lake"."data_warehouse"."my_first_dbt_model"
2019-04-17 11:00:53,356 (Thread-1): PrestoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Unsupported combination of operations in a single transaction", query_id=20190417_100053_14524_n2dpt)
2019-04-17 11:00:53,357 (Thread-1): On my_first_dbt_model: ROLLBACK
2019-04-17 11:00:53,486 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '21b2a51d-7aad-49f7-93ad-10774f7455f8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1a4d510320>]}
2019-04-17 11:00:54,285 (Thread-1): 11:00:54 | 1 of 1 ERROR creating view model data_warehouse.my_first_dbt_model... [ERROR in 1.01s]
2019-04-17 11:00:54,294 (MainThread): 11:00:54 | 
2019-04-17 11:00:54,294 (MainThread): 11:00:54 | Finished running 1 view models in 3.01s.
2019-04-17 11:00:54,300 (MainThread): 
2019-04-17 11:00:54,301 (MainThread): Completed with 1 errors:
2019-04-17 11:00:54,301 (MainThread): 
2019-04-17 11:00:54,301 (MainThread): Runtime Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
2019-04-17 11:00:54,301 (MainThread):   PrestoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Unsupported combination of operations in a single transaction", query_id=20190417_100053_14524_n2dpt)
2019-04-17 11:00:54,301 (MainThread): 
Done. PASS=0 ERROR=1 SKIP=0 TOTAL=1
2019-04-17 11:00:54,302 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1a4d6369b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1a4d60d198>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1a4d632940>]}
2019-04-17 11:00:54,900 (MainThread): Flushing usage events
2019-04-17 11:00:54,926 (MainThread): sys:1: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('<IP_ADDRESS>', 42350), raddr=('<IP_ADDRESS>, 8889)>
```

### Steps to reproduce
Run the commands above.

**Comment by rmgpinto** [comment]
@drewbanin can you take a look at this please?

**Comment by drewbanin** [comment]
Hey @rmgpinto - sorry, I think I missed this when you reopened it!

We've tested this adapter with Presto v0.214 and v0.215 - do you know which version you're using?

I think this might be related to the Presto setting `hive.allow-rename-table=true`. If this is set to `false`, then Presto won't let dbt rename tables.

Our test config looks like:
```
# etc/catalog/hive.properties

connector.name=hive-hadoop2
hive.metastore.uri=thrift://hive-metastore:9083

# Required for dbt
hive.allow-drop-table=true
hive.allow-add-column=true
hive.allow-drop-column=true
hive.allow-rename-table=true
hive.allow-rename-column=true
hive.metastore-cache-ttl=0s
hive.hdfs.authentication.type=NONE
hive.hdfs.impersonation.enabled=false
hive.fs.cache.max-size=10
hive.max-partitions-per-scan=100
```

You can check out the full config here: https://github.com/fishtown-analytics/dbt-presto/blob/master/docker/presto/etc/catalog/hive.properties

Let me know if this works for you!

**Comment by rmgpinto** [comment]
I'm using version 0.215 with a file base authorization, so those settings are set on a separate file: [link](https://prestodb.github.io/docs/current/connector/hive-security.html#hive-file-based-authorization) 

authorizations.json
```
{
  "schemas": [
    {
      "user": "hadoop",
      "schema": ".*",
      "owner": true
    },
    {
      "schema": "default",
      "owner": true
    }
  ],
  "tables": [
    {
      "user": "hadoop",
      "table": ".*",
      "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP", "GRANT_SELECT"]
    },
    {
      "schema": "default",
      "table": ".*",
      "privileges": ["SELECT"]
    }
  ]
}
```

Even if I try to enable those settings in the `hive.properties` file, presto won't start:
```
2019-04-24T13:22:31.149Z        WARN    main    Bootstrap
2019-04-24T13:22:31.349Z        ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Configuration property 'hive.allow-add-column' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

2) Configuration property 'hive.allow-drop-column' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

3) Configuration property 'hive.allow-drop-table' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

4) Configuration property 'hive.allow-rename-column' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

5) Configuration property 'hive.allow-rename-table' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

5 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'hive.allow-add-column' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

2) Configuration property 'hive.allow-drop-column' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

3) Configuration property 'hive.allow-drop-table' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

4) Configuration property 'hive.allow-rename-column' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

5) Configuration property 'hive.allow-rename-table' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

5 errors
```

The user can perform `ALTER` statements. Just not `ALTER` and `DROP` in a transaction, as dbt is sending them.

**Comment by drewbanin** [comment]
I see - thanks for the additional info. We're somewhat new to Presto - do you understand how this could work for us in development, but fail for you? I've definitely successfully run
```
begin;
drop ...;
create ...;
rename ...;
commit;
```

against Presto successfully before!

While it would be good to get to the bottom of this, it might turn out that we're better off avoiding transactions altogether on Presto. Our impression is that Presto doesn't like them very much, and there might be other approaches that can guarantee us query consistency without any of the headaches

**Comment by rmgpinto** [comment]
I've tried to run the statements, but presto gives the same error:
```
presto> START TRANSACTION;
START TRANSACTION
presto> create table
     ->     "data_lake"."data_warehouse"."my_first_dbt_model__dbt_tmp"
     ->   as (
     ->     -- Welcome to your first dbt model!
     -> -- Did you know that you can also configure models directly within
     -> -- the SQL file? This will override configurations stated in dbt_project.yml
     ->
     -> -- Try changing 'view' to 'table', then re-running dbt
     ->
     ->
     ->
     -> select 1 as id
     ->   );
CREATE TABLE: 1 row

Query 20190425_141632_00789_g84nr, FINISHED, 5 nodes
Splits: 102 total, 102 done (100.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

presto> alter table "data_lake"."data_warehouse"."my_first_dbt_model__dbt_tmp" rename to "data_lake"."data_warehouse"."my_first_dbt_model";
Query 20190425_141639_00790_g84nr failed: Unsupported combination of operations in a single transaction
```

**Comment by rmgpinto** [comment]
Here it states that Hive transactions on S3 are not possible: [https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-hive-differences.html](link).
Is there any way I can use dbt with presto and avoid transactions?

**Comment by drewbanin** [comment]
@rmgpinto hmm, ok, thanks for the additional info.

Do you have any ideas about how to ensure consistency without transactions? dbt typically works by dropping existing tables/views and then rebuilding them. If something fails during the rebuild, then transactions help ensure that the database is left in a good state.

Some databases have constructs like `create or replace table` which are atomic mechanisms for overwriting tables, but I don't believe that's supported on Presto. Really curious to hear what you think!

**Comment by rmgpinto** [comment]
@drewbanin at the moment we create snapshot tables and have a "rolling view" pointing to them.
Example:
```
...
t_fact_revenue_20190423 (table) <- v_fact_revenue (view)
t_fact_revenue_20190424 (building table...)
```
After the `CREATE TABLE` is finished on `t_fact_revenue_20190424`, the view is altered to point to that table. If the `CREATE TABLE` fails, the consistency is guaranteed because the `ALTER VIEW` statement is skipped.

I haven't tried, but I think within dbt models I could replicate something similar, ie, generating tables and then views that point to those tables. I'd really like to switch to dbt, there's too many features that add a lot of value on building the models and exploring them with auto-documentation.

Regarding the transactions, I've replaced the following methods on `dbt/adapters/presto/connections.py`:

```
def commit(self):
    pass

def rollback(self):
    pass

def start_transaction(self):
    pass

def add_begin_query(self, name):
    connection = self.get(name)
    with self.exception_handler('handle.start_transaction()', name):
        pass
```

But there's still a `START TRANSACTION` before these queries:
```
select
      table_catalog as database,
      table_name as name,
      table_schema as schema,
      case when table_type = 'BASE TABLE' then 'table'
           when table_type = 'VIEW' then 'view'
           else table_type
      end as table_type
    from "data_lake".information_schema.tables
    where regexp_like(table_schema, '(?i)\Adata_warehouse\Z')

select distinct schema_name
    from "data_lake".information_schema.schemata
    where catalog_name='data_lake'
```

**Comment by drewbanin** [comment]
That's a cool approach! Do you keep the date-suffixed tables around forever? Or do you expire them at some point?

**Comment by rmgpinto** [comment]
I keep them for a month, but that's configurable on the process that does the cleanup.

**Comment by drewbanin** [comment]
That makes sense, thanks for the additional info. You should be able to implement the approach you're describing with a custom materialization. You can make your own materializations and drop them into your `macros/` dir - dbt will pick them up and prefer them over built-in materializations. You can find the docs on this [here](https://docs.getdbt.com/docs/creating-new-materializations).

If you're already tweaking the adapter Python code, you may be able to use the `adapter.clear_transaction()` method to make sure that a transaction isn't open when a new connection is created. I don't have the bandwidth to dig to deep into this (nor do I have a presto cluster to test against at the moment....) but am very happy to help out however I can!

**Comment by rmgpinto** [comment]
I've changed `IsolationLevel.SERIALIZABLE` to `IsolationLevel.AUTOCOMMIT` and it works now.
Thanks for all the help @drewbanin.

**Comment by drewbanin** [comment]
Ok, that's great! Glad you got it working. Will definitely revisit this thread when we have another Presto cluster to test against. Thanks again for all of your insight :)
